module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  safelist: [
    // Add all the dynamic color classes you're using
    'bg-blue-500',
    'bg-blue-600',
    'bg-green-500',
    'bg-green-600',
    'bg-purple-500',
    'bg-purple-600',
    'bg-orange-500',
    'bg-orange-600',
    'bg-red-500',
    'bg-red-600',
    'bg-indigo-500',
    'bg-indigo-600',
    'text-blue-500',
    'text-blue-600',
    'text-green-500',
    'text-green-600',
    'text-purple-500',
    'text-purple-600',
    'text-orange-500',
    'text-orange-600',
    'text-red-500',
    'text-red-600',
    'text-indigo-500',
    'text-indigo-600',
    'border-blue-500',
    'border-green-500',
    'border-purple-500',
    'border-orange-500',
    'border-red-500',
    'border-indigo-500',
    // You can also use patterns for more flexibility
    { pattern: /bg-(blue|green|purple|orange|red|indigo)-(100|500|600)/ },
    { pattern: /text-(blue|green|purple|orange|red|indigo)-(500|600|700)/ },
    { pattern: /border-(blue|green|purple|orange|red|indigo)-500/ },
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}